### ISSUE TITLE
Heads

### ISSUE THREAD

**Issue by teaddicted** [FORTH-ModelBasedTracker/PyOpenPose#60]
Hey,

Is there any way to create a head only net? I mean I want to detect bounding boxes of all the people + their heads only.

Thanks.

**Comment by christian-lanius** [comment]
If you were to have a heads only net, you could not properly generate the bounding box of the people right? Openpose already supports extracting the pose and the location of facial keypoints. Calculating the bounding boxes from these two sets of keypoints should be trivial.
If you only care about bounding boxes, openpose (and thus pyopenpose) might be overkill.  There are other, often RCNN based, detectors available online which only report back the bounding boxes instead of all detected keypoints.

**Comment by teaddicted** [comment]
I only care about the bounding boxes. Right now I'm using yolo v3 which is working quite good but the thing is coco model detects humans pretty accurately but most of the time heads(trained with Hollywood+SCUT head datasets) are not detected. So I'm thinking about trying openpose, time is not an issue so if something is highly accurate I'll be happy to accept it.
Next thing I'm gonna do is use google open images dataset with yolo and faster rcnn I guess it'll work good enough.

**Comment by christian-lanius** [comment]
I have not tried out the face keypoint detection of openpose, but you could certainly try a easy enough approximation of the face bounding box using various keypoints. you could try some example images and see if you can extract the face bounding box using the ear or shoulder keypoints. That should work okayish I'm guessing.
